services:
  - type: web
    name: your-app-name
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && python manage.py migrate && gunicorn product_info.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0  # or whatever version you're using